apiVersion: v1
kind: Pod
metadata:
  name: streamlit-pod
  labels:
    name: streamlit-pod
    app: iris-demo-app
spec:
  containers:
    - name: streamlit-pod
      image: abhishek8988/iris-predict-streamlitapp:1.0
      ports:
        - containerPort: 8501