apiVersion: v1
kind : Service
metadata:
  name: mysql-service
  namespace: mysql-ns
spec:
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: mysql-demo
    app: mysql-app

